### ISSUE TITLE
Add Travis Support (or Maybe Try GitHub Actions) for Website Build

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-website#6]
Here's what I was using: 

```yaml
- language: ruby
      before_install:
        - cd docs/
      rvm:
        - 2.4
      script:
        - bundle exec jekyll build --future
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --disable_external	
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
```
